### ISSUE TITLE
Issue in getScope API

### ISSUE THREAD

**Issue by hrishekesh** [seeden/rbac#10]
Hi Zlatko Fedor,

I have used your module in the following way (code snippet provided below) to implement role based access. I have encountered an issue in the file https://github.com/seeden/rbac/blob/master/dist/rbac.js
on line number 580. When I call the getScope API, items object is null for all other roles. I was able to use the module by replacing the old format of for loop by the new for loop
line 580 - as of today: for (var i = 0; i < items.length; i++)
line 580 - which I suggest: for(var i in items)

Request you to please review this issue and the suggested. I am trying to use this brilliant module in an application. Please let me know your response on this. Below is the code snippet of how I am using the module. Please let me know in case the usage is incorrect.

```js
var RBAC = require('rbac');
var secure = require('rbac/controllers/express');

//create a new RBAC object
var rbac = new RBAC({
    roles        : ['superadmin', 'admin', 'user', 'guest'],
    permissions  : {
        user     : ['create', 'delete'],
        password : ['change', 'forgot'],
        article  : ['create'],
        rbac     : ['update']
    },
    grants: {
        guest: ['create_user', 'forgot_password'],
        user: ['change_password'],
        admin: ['user', 'delete_user', 'update_rbac', 'create_article'],
        superadmin: ['admin']
    }
}, function(err, rbac) {
                
    if(err) {
        throw err;
                                }
   
                app.use(function(req, res, next){
                req.user = rbac;
                req.user.getScope('admin', function(err, permissions){
                                for(var i in permissions){
                                                var containsFlag= false;
                                                if(permissions[i]==='create_article'){
                                                                containsFlag = true;
                                                                break;
                                                }
                                }
                                if(containsFlag){
                                                res.send('Hello Admin!!');
                                                }else{
                                                res.send('Access Denied!');
                                                }
                });
});
                //set up express routes
                    app.use('/admin', secure.hasRole(rbac, 'admin'), adminController);
});
```
In case you have any queries, please write back to me.

Thanks and Regards,
Hrishekesh

**Comment by seeden** [comment]
Hi @hrishekesh.
I am not able to reproduce your issue.
I tested your settings. It is working fine with the current version and old version too.
I updated babel and tests. Please take a look on the latest test in the tests directory. There is exactly your version of the rbac and it is working.

Let me know if it is working for you too with the latest version.
Thanks
