### ISSUE TITLE
where are you using rbac | QUESTION FOR ALL

### ISSUE THREAD

**Issue by seeden** [seeden/rbac#12]
Hi guys.

I would like to hear where are you using this library.
Please add a link to your project.

Thank you

**Comment by BruceHem** [comment]
can't seem to understand the library.

**Comment by seeden** [comment]
why @BruceHem ?

**Comment by BruceHem** [comment]
Very little examples, do you know where i can read more about this?

**Comment by seeden** [comment]
You can find a lot of information in this paper 
http://csrc.nist.gov/rbac/sandhu-ferraiolo-kuhn-00.pdf
