### ISSUE TITLE
Confused about grants

### ISSUE THREAD

**Issue by anhldbk** [seeden/rbac#28]
Hi guys, In the sample code we have:
```js
import RBAC from 'rbac'; // ES5 var RBAC = require('rbac').default;
const rbac = new RBAC({
  roles: ['superadmin', 'admin', 'user', 'guest'],
  permissions: {
    user: ['create', 'delete'],
    password: ['change', 'forgot'],
    article: ['create'],
    rbac: ['update']
  },
  grants: {
    guest: ['create_user', 'forgot_password'],
    user: ['change_password'],
    admin: ['user', 'delete_user', 'update_rbac'], 
    superadmin: ['admin']
  }
}, function(err, rbacInstance) {
  if (err) {
    throw err;
  }
});
```
So what does `'user'` in ` admin: ['user', 'delete_user', 'update_rbac'] ` mean? It allows admins to `create_user` also, right? The following code does NOT work as I think.

```js
rbac.can("admin", "create", "user", (err, can) => {
	if (can) {
		console.log("Granted"); // expected to have this printed out, but it's NOT
	}
});
```

Would you please tell me what wrong is?

**Comment by KasparTr** [comment]
The grants are not explicit. If I add : `admin: ['user', 'delete_user', 'update_rbac', 'create_article'],`
to Grants, the following still doesn't pass:

`const can = await rbac.can('admin', 'create', 'article');  // can == false`

**Comment by anhldbk** [comment]
Thank you @serhiisol
