### ISSUE TITLE
Example of using mongoose-hrbac

### ISSUE THREAD

**Issue by emmkong** [seeden/rbac#40]
I wonder how the mongoose-hrbac plugins apply to rbac? do you mind to provide a simple example? many thanks

**Comment by big-kahuna-burger** [comment]
+1, (readme would be nice location for it)

**Comment by big-kahuna-burger** [comment]
By looking at both sources, should be something like this:
```js
new RBAC({
   ...,
   storage: new MongooseRbacPlugin(mongooseSchema, { defaultRole: 'user', defaultPermissions: [] })
})
```

**Comment by reboy** [comment]
> By looking at both sources, should be something like this:
> 
> ```js
> new RBAC({
>    ...,
>    storage: new MongooseRbacPlugin(mongooseSchema, { defaultRole: 'user', defaultPermissions: [] })
> })
> ```

how the mongoose-hrbac plugins apply to rbac。can you  provide a simple example? thanks
