### ISSUE TITLE
Use of role topic

### ISSUE THREAD

**Issue by kohtala** [seeden/rbac#59]
Hi. Repositories using topic [role](https://github.com/topics/role) are mostly repositories for [ansible roles](https://www.ansible.com/). Using it on this repository may attract attention from wrong group.

Would you like to remove it?

`role` is not a [GitHub featured topic](https://github.com/github/explore), so it's use if free. I am not demanding, but just want to raise this in case it is something you were not aware and would like to change.

**Comment by seeden** [comment]
Thanks but I do not agree.
