### ISSUE TITLE
This project is alive?

### ISSUE THREAD

**Issue by alejosv** [seeden/rbac#62]
I like this dependency, but I see that issues already opened without replying, the last commit in the code was last year (b863a464dd80d2b2b8652baf2edcae542e1a9419) and I saw an issue where they were working on version 5 since 2018 (#38). I am worried about implementing this dependency and that it is abandoned the project.

**Comment by seeden** [comment]
Hi @alejosv. It is maintaining. actually I am rewriting the whole package into the typescript because I am going to use it in my new project htttps://www.creolify.com. If you create some merge requests I will check it
